// JsViewerSamples/JSViewer_Vue_Core/ClientApp/src/app/App.vue
<template>
<div class="main">
    <ReportList 
        :reportList="reportList" 
        :selectedReport="selectedReport" 
        :selectReport="selectReport"/>
    <Viewer :reportName="selectedReport"/>
</div>
</template>
<script>
import ReportList from './components/report-list/ReportList.vue';
import Viewer from './components/Viewer.vue';

export default {
    name: 'app',
    components: {
        ReportList, Viewer
    },
    data() {
        return {
            reportList: [],
            selectedReport: ""
        };
    },
    beforeCreate() {
        fetch('reports')
            .then(response => response.json())
            .then(result => {
                if(result.length > 0){
                    this.selectedReport = result[0];
                    this.reportList = result;
                }
            })
            .catch(e => {
                console.log(e);
            });
    },
    methods: {
        selectReport(reportName) {
            this.selectedReport = reportName;
        }
    }
}
</script>
<style>
    .main {
        width: 100%;
        overflow-x: hidden
    }
</style>

// JsViewerSamples/JSViewer_React_Core/ClientApp/src/app/app.js
﻿import React, {Component} from "react";
import '../styles/app.css';
import Viewer from "./components/viewer";
import ReportList from "./components/reportList";

export default class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            reportsList: [],
            selectedReport: ""
        };
    }

    componentWillMount() {
        this.populateReports();
    }

    populateReports() {
        fetch('reports')
            .then(response => response.json())
            .then(result => {
                if(result.length > 0){
                    this.setState({
                        selectedReport: result[0],
                        reportsList: result
                    });
                }
            })
            .catch(e => {
                console.log(e);
            });
    };

    selectReport = (reportName) => {
        this.setState({
            selectedReport: reportName
        });
    };

    render() {
        return (
            <div className="main">
                <ReportList items={this.state.reportsList}
                            selectedReport={this.state.selectedReport}
                            selectReport={this.selectReport}
                />
                <Viewer reportName={this.state.selectedReport}/>
            </div>
        );
    }
}
